### ISSUE TITLE
Missing information in Devices list

### ISSUE THREAD

**Issue by 432teast** [hsainnos/LICSTER#1]
Hi.

Could you please update the devices README file?

- Amazon link of Raspberry Pi with screen is incorrect;
- Additional information regarding the PCB is necessary. What is exactly meant by PCB components?

Maybe its an idea to create a video (series) regarding the set-up and installation? Would help!

You guys are doing a great job, keep it up.

**Comment by hsainnos** [comment]
Hello,

thank you for opening an issue. I have fixed the link and published a list containing the components of the PCB. We are still figuring out in which manor we want to handle the instructions, though a video series would sure be a good option. However, right now we try to publish all the necessary links and information first, that is required to start.

I close this issue since the two requests are fixed. If you have further remarks, feel free to comment.
