### ISSUE TITLE
Change from Raspberry Pi 3 Model B+ to Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by astviken** [hsainnos/LICSTER#15]
I wonder if I can change from Raspberry Pi 3 Model B+ to Raspberry Pi 4 Model B?
Have a little trouble getting hold of Pi 3.
Are there known difficulties / problems with it?

regards, Alex

**Comment by mniedermaier** [comment]
Hello Alex,

we also have some Raspberry Pi 4 and you can use them as an replacement, except the power supply. You have to use a power supply, which is capable to power the Raspberry Pi 4. 

Additional hint: For the SCADA Raspberry Pi it would be great to choose the Raspberry Pi 4, with 2 or 4 GB RAM, because SCADA LTS/BR use a lot RAM. The PLC and HMI are fine with 1GB RAM.

Regards

Matthias
